apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktok
  namespace: tiktok
  labels:
    app: tiktok
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: tiktok
  template:
    metadata:
      labels:
        app: tiktok
    spec:
      containers:
      - name: tiktok
        image: chenrf1121/tiktok:v3
        ports:
        - containerPort: 8090
        readinessProbe:
          tcpSocket:
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8090
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: tiktok-svc
  namespace: tiktok
spec:
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app: tiktok

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tiktok-hpa-c
  namespace: tiktok
  labels:
    app: tiktok-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tiktok
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tiktok-hpa-m
  namespace: tiktok
  labels:
    app: tiktok-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tiktok
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
